version: '3.9'


services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_ROOT_PASSWORD=123456
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=root2
      - POSTGRES_DATABASE=tzuzul
    volumes:
      - postgres:/var/lib/postgressql/data

volumes:
  postgres:
    driver: local